"""
LLM Generator Module
Handles interaction with Groq API for code generation and data insights
"""

import json
from groq import Groq
from typing import Optional, Dict, Any, List
import pandas as pd


class LLMGenerator:
    """Handles LLM interactions for generating visualization code and data insights"""
    
    # System prompt for visualization code generation
    VISUALIZATION_SYSTEM_PROMPT = """You are an expert Python data visualization specialist. Your task is to generate high-quality, production-ready code for creating interactive data dashboards.

## Instructions:
1. Generate ONLY valid JSON, no explanations or markdown
2. Include at least 4 different types of visualizations
3. Include filter configurations
4. Include field cards showing key metrics
5. Make the dashboard fully interactive
6. Use meaningful titles, labels

## Visualization Types:
- bar: Bar charts
- line: Line charts
- pie: Pie charts
- scatter: Scatter plots
- histogram: Histograms
- heatmap: Correlation heatmaps

## Output Format:
Return a JSON object with this structure:
{{
  "title": "Dashboard Title",
  "metrics": [
    {{"label": "Metric Label", "value": "value_expression", "format": "number/currency/percent"}}
  ],
  "visualizations": [
    {{
      "type": "bar/line/pie/scatter/histogram/heatmap",
      "title": "Chart Title",
      "x": "x_column",
      "y": "y_column",
      "options": {{}}
    }}
  ]
}}

Generate the JSON now. Return ONLY valid JSON."""

    # System prompt for LLM-driven dashboard orchestration (ZERO LOCAL HEURISTICS)
    ORCHESTRATION_SYSTEM_PROMPT = """You are an expert data visualization architect. Your task is to design a COMPLETE dashboard specification using ONLY the provided dataset schema and sample rows. You have ZERO access to any external data or heuristics - you must derive ALL decisions from the schema and samples provided.

## CRITICAL RULES (NO EXCEPTIONS):
1. NEVER use fallback values or default data - if a column doesn't exist, you cannot visualize it
2. ALL chart data must be generated by pandas snippets that will be EXECUTED on the backend
3. The frontend will render EXACTLY what you specify - no local smartness or fallbacks
4. You must provide executable pandas code for EVERY visualization and KPI

## Your Job:
1. Analyze the dataset schema (columns, types, semantic categories)
2. Examine the sample rows to understand the data content
3. Choose appropriate chart types based on data types and relationships
4. Define KPIs that make sense for the numeric columns present
5. Create filters based on categorical columns available
6. Write pandas snippets that compute the actual data for each visualization

## Available Chart Types (choose ONLY from these):
- bar: Bar charts (categorical x, numeric y)
- line: Line charts (time series or sequential data)
- area: Area charts (line with fill)
- pie: Pie/donut charts (part-to-whole)
- scatter: Scatter plots (numeric x, numeric y)
- radar: Radar charts (multi-dimensional metrics)
- heatmap: Heatmaps (correlation or density)
- horizontal_bar: Horizontal bar charts
- stacked_bar: Stacked bar charts

## Output Format - MUST be valid JSON:
{{
  "title": "Dashboard Title derived from data",
  "description": "Brief description of what this dashboard shows",
  "metrics": [
    {{
      "id": "unique_metric_id",
      "label": "Display label",
      "pandas_code": "df['column'].sum() or appropriate pandas expression",
      "format": "number|currency|percent",
      "color": "hex_color or null for default"
    }}
  ],
  "visualizations": [
    {{
      "id": "unique_viz_id",
      "type": "bar|line|area|pie|scatter|radar|heatmap|horizontal_bar|stacked_bar",
      "title": "Chart title",
      "x": "x_column_name or null",
      "y": "y_column_name or [y1, y2] for multi-line",
      "group_by": "optional grouping column",
      "aggregation": "sum|mean|count|min|max",
      "limit": 10,
      "pandas_code": "Exact pandas code that returns [{'x': val, 'y': val}, ...]",
      "options": {{"key": "value"}}
    }}
  ],
  "filters": [
    {{
      "id": "unique_filter_id",
      "column": "categorical_column_name",
      "label": "Filter display label",
      "pandas_code": "df[df['column'].isin(selected_values)]"
    }}
  ],
  "layout": {{
    "type": "grid|tabs|free",
    "columns": ["viz_id1", "viz_id2", ...]
  }}
}}

Generate the JSON now. Return ONLY valid JSON with NO explanations."""

    # System prompt for data insights/summary
    INSIGHT_SYSTEM_PROMPT = """You are a data analysis expert. Your task is to analyze data and provide clear, actionable insights.

## Instructions:
1. Provide a comprehensive summary of the dataset
2. Identify key patterns and trends
3. Highlight important metrics and statistics
4. Give actionable insights based on the data
5. Use simple, clear language

## Output Format:
Return a JSON object with this structure:
{{
  "summary": "A 2-3 sentence overview of what this dataset contains",
  "key_insights": [
    "Insight 1",
    "Insight 2",
    "Insight 3"
  ],
  "statistics": {{
    "key_metric_1": "value",
    "key_metric_2": "value"
  }}
}}

Generate the JSON now. Return ONLY valid JSON."""

    def __init__(self, api_key: str):
        """
        Initialize the LLM generator
        
        Args:
            api_key: Groq API key
        """
        self.client = Groq(api_key=api_key)
        self.model = "llama-3.3-70b-versatile"
    
    def generate_visualization_code(
        self, 
        context: str, 
        prefer_d3: bool = True
    ) -> Optional[str]:
        """
        Generate visualization code using Groq LLM
        
        Args:
            context: Dataset context with attributes and sample data
            prefer_d3: Whether to prefer D3.js over Plotly
            
        Returns:
            Generated JSON configuration or None if generation fails
        """
        viz_preference = "Generate visualizations using Recharts (React charting library)." if not prefer_d3 else "Generate creative D3.js-style visualizations."
        
        system_prompt = self.VISUALIZATION_SYSTEM_PROMPT.replace(
            "Generate the JSON now. Return ONLY valid JSON.",
            f"{viz_preference}\n\nGenerate the JSON now. Return ONLY valid JSON."
        )
        
        user_prompt = f"""Based on the following dataset information, generate visualization configuration:

{context}

Generate the JSON now."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,
                max_tokens=4000
            )
            
            generated = response.choices[0].message.content
            
            # Extract JSON from response
            try:
                if "```json" in generated:
                    json_str = generated.split("```json")[1].split("```")[0]
                elif "```" in generated:
                    json_str = generated.split("```")[1].split("```")[0]
                else:
                    json_str = generated
                
                json_obj = json.loads(json_str.strip())
                return json.dumps(json_obj, indent=2)
            except:
                return generated
                
        except Exception as e:
            print(f"Error generating visualization code: {str(e)}")
            return None
    
    def query_data_with_llm(
        self, 
        dataframe: pd.DataFrame, 
        human_query: str
    ) -> Dict[str, Any]:
        """
        Convert human query to pandas query using LLM and execute it.
        
        Args:
            dataframe: The pandas DataFrame to query
            human_query: Natural language query from user
            
        Returns:
            Dictionary containing pandas code, execution result, and LLM explanation
        """
        # Get dataframe info
        columns = list(dataframe.columns)
        dtypes = dataframe.dtypes.to_dict()
        sample_data = dataframe.head(10).to_string()
        
        # Create prompt for converting human query to pandas
        prompt = f"""You are a data analysis expert. Given a pandas DataFrame with the following structure:

Columns: {columns}
Data types: {dtypes}
Sample data (first 10 rows):
{sample_data}

User's natural language query: "{human_query}"

Your task is to:
1. Convert the human query into a pandas operation (filtering, aggregation, etc.)
2. Execute it and provide a clear explanation of the results

IMPORTANT FORMATTING - NO MARKDOWN (# or *):

QUERY_EXPLANATION:
[One sentence explaining what the user is asking in clean point-wise format]

PANDAS_CODE:
```python
# The pandas code to execute (use 'df' as the dataframe variable, store result in 'result' variable)
result = df.your_operation()
```

RESULT_EXPLANATION:
[Format output as clean numbered points with NO markdown headers (#) and NO asterisks (*). Use format:]
1) Summary:
   - One sentence summary

2) Key Points:
   2.1) First point
   2.2) Second point

Example:
1) Summary:
   - The user wants to see total sales by region.

2) Key Points:
   2.1) Data will be grouped by Region column
   2.2) Sum of Sales will be calculated
   2.3) Result will be sorted by total sales descending

Do NOT include any other text or formatting. Start directly with QUERY_EXPLANATION:
if result not available in dataset print "sorry not mentioned in the dataset" in the result explanation and result"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a data analysis expert. Convert natural language queries to pandas code and provide clear explanations in clean point-wise format with NO markdown headers (#) and NO asterisks (*)."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=3000
            )
            
            result = response.choices[0].message.content
            
            # Extract components - be more robust with parsing
            query_explanation = ""
            pandas_code = ""
            result_explanation = ""
            
            # Try to find each section
            if "QUERY_EXPLANATION:" in result:
                query_section = result.split("QUERY_EXPLANATION:")[1]
                if "PANDAS_CODE:" in query_section:
                    query_explanation = query_section.split("PANDAS_CODE:")[0].strip()
                else:
                    query_explanation = query_section.strip()
            
            if "PANDAS_CODE:" in result:
                code_section = result.split("PANDAS_CODE:")[1]
                if "RESULT_EXPLANATION:" in code_section:
                    pandas_code = code_section.split("RESULT_EXPLANATION:")[0].strip()
                    result_explanation = code_section.split("RESULT_EXPLANATION:")[1].strip()
                else:
                    pandas_code = code_section.strip()
            
            # If we still don't have the components, try alternative parsing
            if not query_explanation or not pandas_code:
                # Try to find any python code blocks
                import re
                code_blocks = re.findall(r'```(?:python)?\s*([\s\S]*?)```', result)
                if code_blocks and not pandas_code:
                    pandas_code = code_blocks[0].strip()
                
                # Try to extract explanations
                lines = result.split('\n')
                explanation_lines = []
                for i, line in enumerate(lines):
                    if line.strip() and not line.startswith('```') and 'result' not in line.lower():
                        if not query_explanation:
                            query_explanation = line.strip()
                            break
            
            # Clean up the code
            pandas_code = pandas_code.replace("```python", "").replace("```", "").strip()
            
            # Execute the pandas code
            execution_result = None
            execution_error = None
            result_str = ""
            
            try:
                if pandas_code:
                    # Wrap the code to ensure result is stored in 'result' variable
                    wrapped_code = f"""
{pandas_code}
"""
                    local_namespace = {'df': dataframe, 'pd': pd, 'result': None}
                    exec(wrapped_code, local_namespace)
                    
                    # Try to get the result - check common variable names
                    execution_result = local_namespace.get('result')
                    
                    if execution_result is None:
                        # Try common variable names
                        for var_name in ['output', 'df_result', 'aggregated', 'filtered', 'res']:
                            if var_name in local_namespace:
                                execution_result = local_namespace[var_name]
                                break
                    
                    if execution_result is None:
                        result_str = "Query executed successfully (no return value)"
                    elif isinstance(execution_result, pd.DataFrame):
                        # Convert DataFrame to string for LLM processing
                        result_str = execution_result.to_string()
                        # Also keep structured data for frontend display
                        execution_result = {
                            "columns": execution_result.columns.tolist(),
                            "rows": execution_result.head(100).values.tolist()
                        }
                    else:
                        result_str = str(execution_result)
                        execution_result = str(execution_result)
                
                # Send the pandas result back to LLM for human-readable explanation
                if result_str and not execution_error:
                    explanation_prompt = f"""Given this pandas DataFrame result from the user's query, provide a professional and well-formatted explanation.

Original Query: {human_query}
Pandas Result:\n{result_str}

IMPORTANT FORMATTING INSTRUCTIONS - STRICT RULES:
- Do NOT use markdown headers (### or #)
- Do NOT use asterisks for bullets (*)
- Use ONLY numbered and lettered format: 1) 2.1) 2.2) etc.
- Keep each point under 20 words
- Start with Summary, then Key Points, then Details

Example output format (use this exact structure):
1) Summary:
   - The result shows X increased by Y% from baseline.

2) Key Points:
   2.1) Total records analyzed: 1500
   2.2) Average value: 42.5
   2.3) Notable finding: Values peaked in Q3

3) Details:
   3.1) The upward trend indicates growth
   3.2) Seasonal patterns are visible
   3.3) Data quality is good

Use simple, direct language.

"""
                    
                    try:
                        explanation_response = self.client.chat.completions.create(
                            model=self.model,
                            messages=[
                                {"role": "system", "content": "You are a professional data analyst. Explain results in clean point-wise format with numbered sections, NO markdown headers (#), NO asterisks (*)."},
                                {"role": "user", "content": explanation_prompt}
                            ],
                            temperature=0.3,
                            max_tokens=1500
                        )
                        result_explanation = explanation_response.choices[0].message.content
                    except:
                        # If LLM explanation fails, use a simple fallback
                        result_explanation = f"Query executed. Result:\n{result_str[:500] if len(result_str) > 500 else result_str}"
                        
            except Exception as e:
                execution_error = str(e)
                result_explanation = f"Error executing query: {execution_error}"
            
            return {
                "query_explanation": query_explanation,
                "pandas_code": pandas_code,
                "execution_result": execution_result,
                "result_explanation": result_explanation,
                "error": execution_error
            }
            
        except Exception as e:
            return {
                "query_explanation": "",
                "pandas_code": "",
                "execution_result": None,
                "result_explanation": "",
                "error": str(e)
            }
    
    def generate_data_insights(
        self, 
        dataframe: pd.DataFrame
    ) -> Dict[str, Any]:
        """
        Generate comprehensive data insights using LLM
        
        Args:
            dataframe: The pandas DataFrame to analyze
            
        Returns:
            Dictionary containing summary, insights, and statistics
        """
        # Get dataset info
        columns = list(dataframe.columns)
        shape = dataframe.shape
        dtypes = dataframe.dtypes.to_dict()
        sample_data = dataframe.head(10).to_string()
        
        # Get basic statistics
        numeric_cols = dataframe.select_dtypes(include=['number']).columns.tolist()
        stats = {}
        
        for col in numeric_cols[:5]:  # Limit to first 5 numeric columns
            stats[col] = {
                "mean": float(dataframe[col].mean()) if not dataframe[col].isnull().all() else None,
                "median": float(dataframe[col].median()) if not dataframe[col].isnull().all() else None,
                "min": float(dataframe[col].min()) if not dataframe[col].isnull().all() else None,
                "max": float(dataframe[col].max()) if not dataframe[col].isnull().all() else None,
                "null_count": int(dataframe[col].isnull().sum())
            }
        
        prompt = f"""Analyze this dataset and provide insights:

Dataset Shape: {shape[0]} rows, {shape[1]} columns
Columns: {columns}
Data Types: {dtypes}

Sample Data:
{sample_data}

Key Statistics (for numeric columns):
{json.dumps(stats, indent=2)}

Based on this data, provide a summary and key insights."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.INSIGHT_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.5,
                max_tokens=3000
            )
            
            result = response.choices[0].message.content
            
            # Try to parse as JSON
            try:
                if "```json" in result:
                    json_str = result.split("```json")[1].split("```")[0]
                elif "```" in result:
                    json_str = result.split("```")[1].split("```")[0]
                else:
                    json_str = result
                
                insights = json.loads(json_str.strip())
                return {
                    "summary": insights.get("summary", result[:500]),
                    "key_insights": insights.get("key_insights", []),
                    "statistics": insights.get("statistics", stats),
                    "raw_insights": result
                }
            except:
                return {
                    "summary": result[:500] if len(result) > 500 else result,
                    "key_insights": result.split('\n')[:5],
                    "statistics": stats,
                    "raw_insights": result
                }
                
        except Exception as e:
            return {
                "summary": f"Error generating insights: {str(e)}",
                "key_insights": [],
                "statistics": stats,
                "error": str(e)
            }
    
    def generate_dashboard_spec(
        self, 
        dataframe: pd.DataFrame
    ) -> Optional[Dict[str, Any]]:
        """
        Generate a COMPLETE dashboard specification using LLM with ZERO local heuristics.
        
        The LLM chooses all charts, KPIs, and filters based ONLY on the dataset schema
        and sample rows. Returns executable pandas snippets that the backend executes.
        
        Args:
            dataframe: The pandas DataFrame to visualize
            
        Returns:
            Dictionary containing complete dashboard spec or None if generation fails
        """
        # Get dataset info - this is the ONLY context the LLM has
        columns = list(dataframe.columns)
        shape = dataframe.shape
        dtypes = {col: str(dtype) for col, dtype in dataframe.dtypes.items()}
        
        # Classify columns semantically
        numeric_cols = dataframe.select_dtypes(include=['number']).columns.tolist()
        categorical_cols = dataframe.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
        datetime_cols = dataframe.select_dtypes(include=['datetime64', 'datetime64[ns]']).columns.tolist()
        
        # Get sample data for context
        sample_data = dataframe.head(5).where(dataframe.head(5).notna(), None).to_dict(orient='records')
        
        # Get unique value counts for categorical columns (for filter suggestions)
        categorical_info = {}
        for col in categorical_cols[:5]:  # Limit to first 5
            categorical_info[col] = {
                "unique_count": int(dataframe[col].nunique()),
                "sample_values": [str(v) for v in dataframe[col].dropna().unique()[:10]]
            }
        
        # Get statistics for numeric columns
        numeric_stats = {}
        for col in numeric_cols[:5]:  # Limit to first 5
            if not dataframe[col].isnull().all():
                numeric_stats[col] = {
                    "mean": float(dataframe[col].mean()),
                    "min": float(dataframe[col].min()),
                    "max": float(dataframe[col].max()),
                    "sum": float(dataframe[col].sum())
                }
        
        # Build context for LLM
        context = f"""DATASET SCHEMA (USE THIS ONLY - NO FALLBACKS):
- Total Rows: {shape[0]}
- Total Columns: {shape[1]}

COLUMNS AND TYPES:
{json.dumps(dtypes, indent=2)}

NUMERIC COLUMNS (for KPIs and y-axes):
{json.dumps(numeric_cols, indent=2)}

CATEGORICAL COLUMNS (for filters, group-by, pie charts):
{json.dumps(categorical_cols, indent=2)}

DATETIME COLUMNS (for time series):
{json.dumps(datetime_cols, indent=2)}

CATEGORICAL VALUE SAMPLES:
{json.dumps(categorical_info, indent=2)}

NUMERIC STATISTICS:
{json.dumps(numeric_stats, indent=2)}

SAMPLE DATA (first 5 rows):
{json.dumps(sample_data, indent=2)}

REMEMBER: You must create visualizations using ONLY these columns. If there are no numeric columns, you cannot create bar charts or line charts. If there are no categorical columns, you cannot create pie charts or filters."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.ORCHESTRATION_SYSTEM_PROMPT},
                    {"role": "user", "content": context}
                ],
                temperature=0.2,  # Low temperature for deterministic output
                max_tokens=6000
            )
            
            generated = response.choices[0].message.content
            
            # Extract JSON from response
            try:
                if "```json" in generated:
                    json_str = generated.split("```json")[1].split("```")[0]
                elif "```" in generated:
                    json_str = generated.split("```")[1].split("```")[0]
                else:
                    json_str = generated
                
                dashboard_spec = json.loads(json_str.strip())
                return dashboard_spec
                
            except json.JSONDecodeError as e:
                print(f"JSON parsing error: {e}")
                print(f"Raw response: {generated[:500]}")
                return None
                
        except Exception as e:
            print(f"Error generating dashboard spec: {str(e)}")
            return None
    
    def execute_dashboard_spec(
        self, 
        dataframe: pd.DataFrame, 
        dashboard_spec: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Execute the pandas snippets in the dashboard spec to produce visualization data.
        
        Args:
            dataframe: The pandas DataFrame
            dashboard_spec: The LLM-generated dashboard specification
            
        Returns:
            Dictionary with executed data for all visualizations and KPIs
        """
        results = {
            "title": dashboard_spec.get("title", "Data Dashboard"),
            "description": dashboard_spec.get("description", ""),
            "metrics": [],
            "visualizations": [],
            "filters": dashboard_spec.get("filters", []),
            "errors": []
        }
        
        # Execute metric calculations
        for metric in dashboard_spec.get("metrics", []):
            metric_id = metric.get("id", "unknown")
            pandas_code = metric.get("pandas_code", "")
            
            try:
                local_ns = {'df': dataframe, 'pd': pd, 'np': __import__('numpy')}
                exec(f"result = {pandas_code}", local_ns)
                value = local_ns.get('result')
                
                # Convert to Python types
                if hasattr(value, 'item'):
                    value = value.item()
                elif hasattr(value, 'tolist'):
                    value = value.tolist()
                
                results["metrics"].append({
                    "id": metric_id,
                    "label": metric.get("label", metric_id),
                    "value": value,
                    "format": metric.get("format", "number"),
                    "color": metric.get("color")
                })
            except Exception as e:
                results["errors"].append(f"Metric {metric_id}: {str(e)}")
        
        # Execute visualization data calculations
        for viz in dashboard_spec.get("visualizations", []):
            viz_id = viz.get("id", "unknown")
            pandas_code = viz.get("pandas_code", "")
            
            try:
                local_ns = {'df': dataframe, 'pd': pd, 'np': __import__('numpy')}
                exec(pandas_code, local_ns)
                data = local_ns.get('result')
                
                # Convert DataFrame to list of dicts if needed
                if isinstance(data, pd.DataFrame):
                    data = data.to_dict(orient='records')
                elif hasattr(data, 'tolist'):
                    data = data.tolist()
                
                results["visualizations"].append({
                    "id": viz_id,
                    "type": viz.get("type", "bar"),
                    "title": viz.get("title", viz_id),
                    "data": data,
                    "x": viz.get("x"),
                    "y": viz.get("y"),
                    "options": viz.get("options", {})
                })
            except Exception as e:
                results["errors"].append(f"Visualization {viz_id}: {str(e)}")
        
        return results
